# Generated by Django 5.0.2 on 2024-02-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetacking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
