# Generated by Django 5.0.2 on 2024-02-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagetacking_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
