# Generated by Django 4.2.9 on 2024-03-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_positiontracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetacking',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
