# Generated by Django 4.2.9 on 2024-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_imagetacking_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetacking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
