# Generated by Django 5.0.3 on 2024-03-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_imagetacking_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
            ],
        ),
    ]
