# Generated by Django 5.0.3 on 2024-03-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_detectionresults_result_detectionresults_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetacking',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
